import {createRequire} from 'node:module';
import {mkdir,writeFile} from 'node:fs/promises';
import assert from 'node:assert/strict';
import * as THREE from 'three';
import {exhibits} from '../src/exhibits.ts';
const require=createRequire(import.meta.url),{chromium}=require(process.argv[2]||'playwright'),base=process.env.BASE_URL||'http://127.0.0.1:5173';
const browser=await chromium.launch({channel:'msedge',headless:true,args:['--enable-webgl']});const page=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[];page.on('pageerror',e=>errors.push(e.message));const s=exhibits.find(s=>s.kind==='flute');
await page.addInitScript(()=>{window.__audio=[];window.__notes=[];const A=window.AudioContext;window.AudioContext=class extends A{constructor(...a){super(...a);window.__audio.push(this)}createOscillator(){const o=super.createOscillator(),start=o.start.bind(o);o.start=(...args)=>{window.__notes.push(o.frequency.value);start(...args)};return o}}});await mkdir('artifacts',{recursive:true});
const progress=()=>page.evaluate(id=>JSON.parse(localStorage.getItem(`culture-slice:exhibit:${id}:v1`)),s.id);
try{
 await page.goto(`${base}/#/scene/${s.id}`,{waitUntil:'networkidle'});await page.getByRole('button',{name:'开始探索',exact:true}).click();await page.mouse.move(10,10);await page.waitForTimeout(1500);assert.equal(await page.getByRole('tooltip').count(),0);assert.equal(await page.evaluate(()=>window.__notes.length),0);
 await page.screenshot({path:'artifacts/flute-refined-overview.png',fullPage:true});
 const r=await page.locator('canvas').boundingBox(),cam=new THREE.OrthographicCamera(-r.width/2,r.width/2,r.height/2,-r.height/2,.1,80);cam.position.set(8,9.65,12);cam.lookAt(0,.65,0);cam.zoom=Math.min(62,r.width/18.5,r.height/14.5);cam.updateProjectionMatrix();cam.updateMatrixWorld();const p=new THREE.Vector3(-.35,.39,1.55).project(cam);await page.mouse.move(r.x+(p.x+1)*r.width/2,r.y+(1-p.y)*r.height/2);await page.getByRole('tooltip',{name:'七孔骨笛',exact:true}).waitFor();assert.equal(await page.getByRole('tooltip').evaluate(e=>getComputedStyle(e).pointerEvents),'none');await page.mouse.down();await page.mouse.up();await page.getByRole('heading',{name:'七孔骨笛',exact:true}).waitFor();await page.mouse.move(10,10);
 await page.getByRole('button',{name:s.steps[0].label,exact:true}).click();await page.waitForTimeout(400);await page.getByRole('button',{name:'取消操作',exact:true}).click();assert.deepEqual((await progress()).actions,[]);assert.equal(await page.evaluate(()=>window.__audio.every(a=>a.state==='closed')),true);
 await page.getByRole('button',{name:'关闭声音',exact:true}).click();const before=await page.evaluate(()=>window.__notes.length);await page.getByRole('button',{name:s.steps[0].label,exact:true}).click();await page.waitForFunction(id=>JSON.parse(localStorage.getItem(`culture-slice:exhibit:${id}:v1`)).actions.length===1,s.id);assert.equal(await page.evaluate(()=>window.__notes.length),before);await page.getByRole('button',{name:'开启声音',exact:true}).click();
 for(const step of s.steps.slice(1)){await page.getByRole('button',{name:step.label,exact:true}).click();await page.waitForTimeout(600);await page.screenshot({path:`artifacts/flute-${step.id}-motion.png`,fullPage:true});await page.waitForFunction(({id,step})=>JSON.parse(localStorage.getItem(`culture-slice:exhibit:${id}:v1`)).actions.includes(step),{id:s.id,step:step.id});}
 await page.getByRole('button',{name:'关闭探索回顾',exact:true}).click();await page.getByRole('button',{name:'试听较低音',exact:true}).click();await page.waitForTimeout(700);await page.screenshot({path:'artifacts/flute-low-detail.png',fullPage:true});await page.getByRole('button',{name:'试听较高音',exact:true}).click();await page.waitForTimeout(700);await page.screenshot({path:'artifacts/flute-high-detail.png',fullPage:true});assert.deepEqual((await progress()).actions,['low','high','listen']);const notes=await page.evaluate(()=>window.__notes);assert.ok(notes.includes(330)&&notes.includes(495));
 for(const o of s.objects){await page.locator('.object-switcher').getByRole('button',{name:new RegExp(o.name)}).click();await page.getByRole('heading',{name:o.name,exact:true}).waitFor();await page.waitForTimeout(1100);await page.screenshot({path:`artifacts/flute-object-${o.id}.png`,fullPage:true});}
 await page.getByRole('button',{name:'问一问',exact:true}).click();await page.getByRole('button',{name:s.qa[0].question,exact:true}).click();await page.locator('.message.assistant').waitFor();assert.ok(await page.locator('.message.assistant a').count());
 await page.getByRole('button',{name:'返回全景',exact:true}).click();await page.getByRole('button',{name:'收起手册',exact:true}).click();await page.waitForTimeout(1300);await page.screenshot({path:'artifacts/flute-refined-wide.png',fullPage:true});if(process.env.CAPTURE_COVERS==='1')await page.locator('canvas').screenshot({path:'public/images/prehistory-culture.png'});
 await page.reload({waitUntil:'networkidle'});assert.equal((await progress()).actions.length,3);await page.setViewportSize({width:390,height:844});await page.waitForTimeout(1300);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await page.screenshot({path:'artifacts/flute-refined-mobile.png',fullPage:true});await page.getByRole('link',{name:'返回时间轴',exact:false}).click();assert.equal(await page.locator('canvas').count(),0);assert.equal(await page.evaluate(()=>window.__audio.every(a=>a.state==='closed')),true);
 assert.deepEqual(errors,[]);const result={checks:['five targets and focus','real pointer hover and click','mute and cancel close audio','two synthesized pitches','all steps and replay notes preserve progress','source citation','reload','390px layout','leave releases canvas and audio'],notes,errors};await writeFile('artifacts/flute-refinement-results.json',JSON.stringify(result,null,2));console.log(JSON.stringify(result,null,2));
}finally{await browser.close();}
