import {useEffect,useMemo,useRef,useState,type FormEvent,type CSSProperties} from 'react';
import {getExhibit,exhibitPreset,exhibitSources} from './exhibits';
import {completeStep,createActionClock,exhibitKey,freshExhibit,restoreExhibit,LAST_SCENE_KEY} from './exhibit-state';
import ExhibitScene from './ExhibitScene';
import {eras,scenes} from './catalog';
import './exhibits.css';
import {fluteNotes} from './flute-demo';
import {bellNotes} from './bell-demo';
type Message={role:'user'|'assistant';content:string;sourceIds?:string[];mode?:string};
export default function ExhibitExperience({sceneId}:{sceneId:string}){
 const scene=getExhibit(sceneId)!;
 const [progress,setProgress]=useState(()=>{try{return restoreExhibit(scene,localStorage.getItem(exhibitKey(sceneId)));}catch{return freshExhibit();}});
 const [selected,setSelected]=useState<string|null>(null),[focus,setFocus]=useState<string|null>(null),[tab,setTab]=useState<'object'|'chat'|'sources'>('object'),[panel,setPanel]=useState(true),[resetCamera,setResetCamera]=useState(0),[variant,setVariant]=useState(.35),[busy,setBusy]=useState(false),[recap,setRecap]=useState(false),[sound,setSound]=useState(true),[storageFailed,setStorageFailed]=useState(false),[quiz,setQuiz]=useState<number|null>(null);
 const [messages,setMessages]=useState<Message[]>([]),[question,setQuestion]=useState(''),[pending,setPending]=useState(false),[error,setError]=useState(''),[retry,setRetry]=useState(''),[connected,setConnected]=useState(false),[audioError,setAudioError]=useState('');
 const audio=useRef<AudioContext|null>(null),request=useRef<AbortController|null>(null),bar=useRef<HTMLSpanElement>(null),dialog=useRef<HTMLDialogElement>(null),answerEnd=useRef<HTMLDivElement>(null),alive=useRef(true);
 const clock=useMemo(()=>createActionClock(id=>{setProgress(p=>completeStep(scene,p,id));if(id===scene.steps.at(-1)?.id)setRecap(true);},setBusy),[scene]);
 const stage=progress.actions.length,done=stage===scene.steps.length,object=scene.objects.find(o=>o.id===selected),next=scene.steps[stage],era=eras.find(e=>e.id===scene.eraId)!;
 useEffect(()=>{try{localStorage.setItem(exhibitKey(sceneId),JSON.stringify(progress));if(progress.entered)localStorage.setItem(LAST_SCENE_KEY,sceneId);}catch{setStorageFailed(true);}},[progress,sceneId]);
 useEffect(()=>{const controller=new AbortController();fetch('/api/status',{signal:controller.signal}).then(r=>r.json()).then(x=>setConnected(x.configured===true)).catch(()=>{});return()=>controller.abort();},[]);
 useEffect(()=>{alive.current=true;return()=>{alive.current=false;clock.cancel(false);request.current?.abort();request.current=null;const a=audio.current;audio.current=null;if(a&&a.state!=='closed')void a.close().catch(()=>{});};},[clock]);
 useEffect(()=>{if(!busy)return;let frame=0,last=performance.now();const tick=(now:number)=>{if(!document.hidden)clock.advance(Math.min(.1,(now-last)/1000));last=now;if(bar.current)bar.current.style.width=`${clock.phase*100}%`;if(clock.running)frame=requestAnimationFrame(tick);};frame=requestAnimationFrame(tick);return()=>cancelAnimationFrame(frame);},[busy,clock]);
 useEffect(()=>{if(recap)dialog.current?.showModal();else dialog.current?.close();},[recap]);
 useEffect(()=>{answerEnd.current?.scrollIntoView({block:'nearest',behavior:matchMedia('(prefers-reduced-motion:reduce)').matches?'instant':'smooth'});},[messages,pending]);
 function stopSound(){const a=audio.current;audio.current=null;if(a&&a.state!=='closed')void a.close().catch(()=>{});}
 function cancel(){clock.cancel();stopSound();setFocus(null);}
 function choose(id:string){cancel();setSelected(id);setProgress(p=>({...p,viewed:[...new Set([...p.viewed,id])]}));setPanel(true);setTab('object');}
 function overview(){cancel();setSelected(null);setResetCamera(n=>n+1);}
 async function play(index:number){
  if(!sound||!['flute','bells'].includes(scene.kind))return;
  try{stopSound();const a=new AudioContext();audio.current=a;await a.resume();if(!alive.current||audio.current!==a)return;const events=scene.kind==='flute'?fluteNotes(index):bellNotes(index);const base=scene.kind==='bells'?220:330;
   for(const {at,note} of events){const o=a.createOscillator(),gain=a.createGain(),flute=scene.kind==='flute';
    if(flute){const real=new Float32Array(5),imag=new Float32Array([0,1,.1,.025,.012]);o.setPeriodicWave(a.createPeriodicWave(real,imag));}else o.type='sine';
    o.frequency.value=base*(note?(flute?1.5:1.25):1);const t=a.currentTime+at,duration=flute?.65:.45;gain.gain.setValueAtTime(0,t);gain.gain.linearRampToValueAtTime(flute?.065:.07,t+(flute?.075:.02));gain.gain.exponentialRampToValueAtTime(.001,t+duration);o.connect(gain);gain.connect(a.destination);o.start(t);o.stop(t+duration+.04);o.onended=()=>{o.disconnect();gain.disconnect();};}
   setAudioError('');}catch{if(alive.current)setAudioError('声音暂不可用，仍可观察模型并完成探索。');}
 }
 function run(){if(!next||busy||scene.kind==='slips'&&stage===1&&quiz!==54)return;setSelected(next.objectId);setFocus(null);setProgress(p=>({...p,viewed:[...new Set([...p.viewed,next.objectId])]}));if(scene.kind==='flute')setVariant(stage===1?1:0);clock.start(next.id,stage,next.duration);void play(stage);if(matchMedia('(prefers-reduced-motion:reduce)').matches)clock.finish();}
 function replay(){cancel();setRecap(false);setQuiz(null);setProgress(p=>({...p,actions:[]}));setSelected(null);setResetCamera(n=>n+1);}
 function reset(){cancel();request.current?.abort();request.current=null;setPending(false);setMessages([]);setError('');setQuestion('');setRetry('');setQuiz(null);setSelected(null);setVariant(.35);setRecap(false);setTab('object');setProgress({...freshExhibit(),entered:true});setResetCamera(n=>n+1);}
 async function ask(text:string,retrying=false){
  if(!text.trim()||pending)return;const q=text.trim().slice(0,1000);setQuestion('');setError('');setRetry(q);const history=messages.slice(-8).map(({role,content})=>({role,content}));if(!retrying)setMessages(m=>[...m,{role:'user',content:q}]);
  if(!connected){const result=exhibitPreset(scene,q,selected,progress.actions);setMessages(m=>[...m,{role:'assistant',content:result.answer,sourceIds:result.sourceIds,mode:'preset'}]);return;}
  const controller=new AbortController();request.current=controller;setPending(true);const timeout=setTimeout(()=>controller.abort(),23000);
  try{const r=await fetch('/api/chat',{method:'POST',headers:{'Content-Type':'application/json'},signal:controller.signal,body:JSON.stringify({sceneId,zoneId:null,objectId:selected,actions:progress.actions,question:q,history:retrying?history.slice(0,-1):history})});const result=await r.json();if(!r.ok)throw new Error(result.error||'暂时无法回答，请重试。');if(request.current!==controller)return;setMessages(m=>[...m,{role:'assistant',content:result.answer,sourceIds:result.sourceIds,mode:result.mode}]);}catch(e){if(request.current===controller)setError(e instanceof Error&&e.name!=='AbortError'?e.message:'回答等待超时，可以重试或先查看资料。');}finally{clearTimeout(timeout);if(request.current===controller){request.current=null;setPending(false);}}
 }
 function submit(e:FormEvent){e.preventDefault();void ask(question);}
 const focusProps=(id:string)=>({onFocus:(e:React.FocusEvent<HTMLButtonElement>)=>{if(e.currentTarget.matches(':focus-visible'))setFocus(id);},onBlur:()=>setFocus(null)});
 return <div className={`app-shell exhibit-shell exhibit-${scene.kind}`} style={{'--exhibit-accent':scene.accent} as CSSProperties}>
 <header className='topbar'><a className='brand' href={`#/era/${scene.eraId}`} aria-label='文化切片首页'><span className='brand-mark'>切</span><span>文化切片<small>CULTURE, UP CLOSE</small></span></a><div className='edition'>{era.title}<span>{scene.subtitle}</span></div><div className='top-actions'><a className='back-timeline' href={`#/era/${scene.eraId}`}>← 返回时间轴</a><button className='icon-button' aria-label='返回全景' title='返回全景' onClick={overview}>⌂</button>{['flute','bells'].includes(scene.kind)&&<button className='icon-button' onClick={()=>{if(sound)stopSound();setSound(!sound);}} aria-label={sound?'关闭声音':'开启声音'} title={sound?'关闭声音':'开启声音'}>{sound?'♫':'♪'}</button>}<button className='icon-button' disabled={!progress.entered} onClick={reset} aria-label='重新开始' title='重新开始'>↺</button></div></header>
 <main className={`experience ${progress.entered&&panel?'with-panel':''}`}>
 <section className='world' aria-label={scene.subtitle}><div className='scene-heading'><div className='eyebrow'><span className='line'/>{scene.culture}</div><h1>{scene.title}<span>{scene.question}</span></h1></div><div className='scene-canvas'><ExhibitScene scene={scene} selected={selected} focus={focus} choose={choose} clock={clock} stage={stage} variant={variant} entered={progress.entered} reset={resetCamera}/></div><div className='scene-corner'><span>{scene.subtitle}</span><span>资料为据 · 艺术演绎</span></div>
 {!progress.entered?<div className='entry-card'><span className='tiny-tag'>{era.title} / {scenes.find(s=>s.id===sceneId)?.category}</span><h2>{scene.question}</h2><p>{scene.description}</p><button className='primary' onClick={()=>setProgress(p=>({...p,entered:true}))}>开始探索 <span aria-hidden="true">→</span></button><span className='entry-note'>约 2–4 分钟 · 可随时继续</span></div>:<><nav className='breadcrumbs' aria-label='场景层级'><button onClick={overview}>场景全景</button>{object&&<><span>／</span><span>{object.name}</span></>}</nav>
 {!panel&&<button className='open-panel' onClick={()=>setPanel(true)}>探索手册 ↗</button>}
 {busy&&<div className='placement-card' role='status'><span>{next?.label}…</span><div className='progress-line'><span ref={bar}/></div><button onClick={()=>{stopSound();clock.finish();}}>跳过动画</button><button onClick={cancel}>取消操作</button></div>}
 <div className='world-bottom'><span className='navigation-help'>{busy?'正在观察变化 · 已锁定视角':'悬停发现物件 · 点击靠近 · 拖动旋转'}</span><div className='object-switcher'>{scene.objects.map((o,i)=><button key={o.id} {...focusProps(o.id)} aria-pressed={o.id===selected} className={o.id===selected?'selected':''} onClick={()=>choose(o.id)}><span>0{i+1}</span>{o.name}{progress.viewed.includes(o.id)&&<span>✓</span>}</button>)}</div></div></>}
 </section>
 {progress.entered&&panel&&<aside className='side-panel' aria-label='探索手册'><div className='panel-header'><span>探索手册</span><button className='icon-button' onClick={()=>setPanel(false)} aria-label='收起手册'>×</button></div><nav className='panel-tabs' aria-label='手册内容'>{(['object','chat','sources'] as const).map((t,i)=><button key={t} onClick={()=>setTab(t)} className={tab===t?'active':''}>{['器物','问一问','资料'][i]}</button>)}</nav>
 {tab==='object'&&<div className='panel-scroll object-detail'><span className='section-index'>{object?'OBJECT / 器物线索':'FIELD NOTES / 场景'}</span><h2>{object?.name||scene.subtitle}</h2><p className='lead'>{object?.fact||scene.description}</p>{object?<><p className='detail-copy'>{object.detail}</p><span className='object-kind'>{object.kind}</span></>:<div className='intro-steps'>{scene.objects.map(o=><button className='region-object' key={o.id} {...focusProps(o.id)} onClick={()=>choose(o.id)}>{o.name}<span aria-hidden="true">→</span></button>)}</div>}
 <section className='exhibit-activity' aria-label='场景互动'><span className='section-index'>动手观察 / {Math.min(stage+1,scene.steps.length)} · {scene.steps.length}</span><h3>{done?'这一轮操作已完成':next?.label}</h3>
 {scene.kind==='flute'&&stage>0&&<div className='exhibit-choice' aria-label='声音对照'><button disabled={busy} aria-pressed={variant<.5} onClick={()=>{choose('flute');setVariant(0);void play(0);}}>试听较低音</button><button disabled={busy} aria-pressed={variant>=.5} onClick={()=>{choose('flute');setVariant(1);void play(1);}}>试听较高音</button></div>}
 {scene.kind==='flute'&&stage>0&&<p className='activity-note'>{sound?'浅绿圆片表示覆孔；排列仅为示意。':'声音已关闭，仍可比较两种孔位。'}</p>}
 {scene.kind==='pottery'&&<div className='exhibit-choice' aria-label='纹样比较'><button aria-pressed={variant<.5} onClick={()=>setVariant(0)}>鱼纹示意</button><button aria-pressed={variant>=.5} onClick={()=>setVariant(1)}>网纹示意</button></div>}
 {scene.kind==='lamp'&&stage>=2&&<label className='exhibit-range'>灯罩开口 · 示意<input type='range' min='0' max='100' value={Math.round(variant*100)} onChange={e=>setVariant(Number(e.target.value)/100)} aria-label='灯罩开口'/><span>收拢 — 展开</span></label>}
 {scene.kind==='slips'&&stage===1&&<div className='exhibit-quiz'><p>先试一试：6 × 9 = ?</p><div className='exhibit-choice'>{[45,54,63].map(n=><button key={n} aria-pressed={quiz===n} onClick={()=>setQuiz(n)}>{n}</button>)}</div>{quiz!==null&&<p role='status'>{quiz===54?'答对了，打开木牍核对。':'还不一致，再数一数六组九。'}</p>}</div>}
 {!done?<button className='primary' disabled={busy||scene.kind==='slips'&&stage===1&&quiz!==54} onClick={run}>{busy?'变化正在发生…':next.label}<span aria-hidden="true">→</span></button>:<><button className='primary' onClick={()=>setRecap(true)}>查看探索回顾 <span aria-hidden="true">→</span></button><button className='text-button' onClick={replay}>重放这一轮操作</button></>}
 {stage>0&&<p className='exhibit-result' role='status'>{scene.steps[stage-1].explanation}</p>}{['bells','flute'].includes(scene.kind)&&<p className='activity-note'>现代合成音 · 不是文物原声或历史曲调</p>}{audioError&&<p role='status'>{audioError}</p>}</section>
 <button className='question-link' onClick={()=>setTab('chat')}>关于{object?.name||'这个场景'}，我还想知道 <span aria-hidden="true">↗</span></button><button className='source-link' onClick={()=>setTab('sources')}>查看资料依据与演绎说明 →</button></div>}
 {tab==='sources'&&<div className='panel-scroll source-detail'><span className='section-index'>BEHIND THE SCENE</span><h2>观察之后，<br/>回到证据。</h2>{exhibitSources(scene,selected).map(s=><section className='reference-entry' key={s.id}><div className='source-card'><span>{s.institution}</span><h3>{s.title}</h3><a href={s.url} target='_blank' rel='noreferrer'>阅读原始资料 ↗</a></div><ul className='fact-list'>{s.facts.map(f=><li key={f}>{f}</li>)}</ul></section>)}<div className='interpretation'><b>哪些属于艺术演绎？</b><p>{scene.interpretation}</p></div></div>}
 {tab==='chat'&&<div className='chat-panel'><div className='chat-context'><div><strong>文化探索向导</strong><span>{connected?'结合当前器物与操作回答':'预置讲解可用 · 自由问答未连接'}</span></div></div><div className='context-chip'>当前关注：{object?.name||scene.subtitle} · 已完成 {stage}/{scene.steps.length} 项操作</div><div className='chat-scroll'><p className='chat-welcome'>从眼前的变化开始，问一个问题。</p><div className='suggestions'>{[...scene.qa.map(q=>q.question),'刚才做了什么？'].map(q=><button key={q} disabled={pending} onClick={()=>void ask(q)}>{q}<span aria-hidden="true">↗</span></button>)}</div>{messages.map((m,i)=><div className={`message ${m.role}`} key={i}><span>{m.role==='user'?'你':m.mode==='preset'?'预置讲解':'文化探索向导'}</span><p>{m.content}</p>{scene.sources.filter(s=>m.sourceIds?.includes(s.id)).map(s=><a key={s.id} href={s.url} target='_blank' rel='noreferrer'>依据：{s.institution}《{s.title}》 ↗</a>)}</div>)}{pending&&<p className='pending' role='status'>正在查阅当前场景资料…</p>}{error&&<div className='error-box' role='alert'>{error}<button onClick={()=>void ask(retry,true)}>重试这个问题</button></div>}<div ref={answerEnd}/></div><form className='chat-form' onSubmit={submit}><label className='sr-only' htmlFor='exhibit-question'>你的问题</label><textarea id='exhibit-question' value={question} maxLength={1000} rows={2} onChange={e=>setQuestion(e.target.value)} placeholder='问问眼前的器物…' onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey&&!e.nativeEvent.isComposing){e.preventDefault();void ask(question);}}}/><button className='send-button' aria-label='发送问题' disabled={pending||!question.trim()}>↑</button></form><p className='chat-footnote'>事实依据可追溯，艺术演绎会注明。</p></div>}
 </aside>}
 </main><footer className='journey exhibit-journey'><span className='journey-title'>{scene.subtitle}</span><ol>{scene.steps.map((s,i)=><li key={s.id} className={i<=stage?'current':''}><span>{i<stage?'✓':`0${i+1}`}</span>{s.label.split('，')[0]}{i<scene.steps.length-1&&<i/>}</li>)}</ol><button disabled={!progress.entered} onClick={()=>setRecap(true)}>我的发现 <span>{progress.viewed.length}/{scene.objects.length}</span></button></footer>
 {storageFailed&&<div className='storage-notice' role='status'>浏览器无法保存进度，本次探索仍可继续。</div>}
 <dialog ref={dialog} className='recap exhibit-recap' onClose={()=>setRecap(false)} onCancel={()=>setRecap(false)}><button className='icon-button recap-close' aria-label='关闭探索回顾' onClick={()=>setRecap(false)}>×</button><span className='section-index'>YOUR FIELD NOTES</span><h2>{scene.title} · 我的发现</h2><p className='recap-intro'>只记录你已看过与做过的事。</p><div className='recap-objects'>{scene.objects.map(o=><div key={o.id} className={progress.viewed.includes(o.id)?'visited':''}><span>{progress.viewed.includes(o.id)?'已观察':'尚未观察'}</span><strong>{o.name}</strong></div>)}</div><div className='recap-facts'>{scene.steps.map(s=><p key={s.id}>{progress.actions.includes(s.id)?'✓':'○'} {s.label}</p>)}</div>{done&&<blockquote>{scene.steps.at(-1)?.explanation}<small>互动是教学示意，依据与限制见资料卡。</small></blockquote>}<button className='primary' onClick={()=>{setRecap(false);setPanel(true);setTab('chat');}}>继续探索与提问 →</button><a className='text-button recap-next' href={`#/era/${scene.eraId}`}>返回{era.title}，选择下一个切片 →</a><button className='text-button' onClick={replay}>重新体验操作</button></dialog>
 </div>;
}
