import {useMemo} from 'react';
import * as T from 'three';
import {Box,Blocks,Stick,type Block} from './DioramaPrimitives';
import type {Point} from './exhibits';
import {inFootprint,type Footprint} from './site-footprints';
export const phase=(v:number,n=0)=>T.MathUtils.clamp(v-n,0,1);
export function Pipe({points,r=.015,c='#60675f',closed=false}:{points:Point[];r?:number;c?:string;closed?:boolean}){const curve=useMemo(()=>new T.CatmullRomCurve3(points.map(p=>new T.Vector3(...p)),closed),[JSON.stringify(points),closed]);return <mesh castShadow><tubeGeometry args={[curve,Math.max(32,points.length*5),r,8,closed]}/><meshStandardMaterial color={c} roughness={.5} metalness={.35}/></mesh>;}
/** Low-level frame only; each building defines its own walls, roof and plan. */
export function WindowFrame({w=1.1,h=1.4,c='#797b65',cols=3,rows=3}:{w?:number;h?:number;c?:string;cols?:number;rows?:number}){return <><Box p={[0,0,0]} s={[w+.12,h+.12,.06]} c={c}/><mesh position={[0,0,.038]}><planeGeometry args={[w,h]}/><meshStandardMaterial color='#9dacaa' roughness={.3} metalness={.2}/></mesh>{Array.from({length:cols+1},(_,i)=><Box key={`v${i}`} p={[-w/2+i*w/cols,0,.06]} s={[.033,h+.06,.055]} c={c}/>)}{Array.from({length:rows+1},(_,i)=><Box key={`h${i}`} p={[0,-h/2+i*h/rows,.06]} s={[w+.07,.032,.055]} c={c}/>)}</>;}
export function Wheel({r=.22,c='#3b4843',spokes=6}:{r?:number;c?:string;spokes?:number}){return <group rotation={[0,Math.PI/2,0]}><mesh castShadow><torusGeometry args={[r,.014,8,56]}/><meshStandardMaterial color={c} metalness={.5} roughness={.45}/></mesh><mesh rotation={[Math.PI/2,0,0]}><cylinderGeometry args={[r*.14,r*.14,.055,20]}/><meshStandardMaterial color={c} metalness={.5}/></mesh>{Array.from({length:spokes},(_,i)=>{const a=i*Math.PI*2/spokes;return <Stick key={i} a={[0,0,0]} b={[Math.cos(a)*r,Math.sin(a)*r,0]} r={r*.06} c={c}/>;})}</group>;}
export function CutGround({outline,top='#b5b4a8',h=.08,paved=true}:{outline:Footprint;top?:string;h?:number;paved?:boolean}){const data=useMemo(()=>{const a:Block[]=[];for(let x=-8;x<=8;x+=.25)for(let z=-6;z<=6;z+=.25){if(!inFootprint(x,z,outline))continue;const n=(Math.sin(x*35+z*61)+1)/2;a.push({p:[x,h-.065,z],s:[.257,.13,.257],c:new T.Color(top).multiplyScalar(.93+n*.1).getStyle()},{p:[x,(h-.46)/2,z],s:[.257,h+.2,.257],c:paved?'#a09988':n>.5?'#a59e85':'#b0a68b'},{p:[x,-.46,z],s:[.257,.10,.257],c:'#858c80'});}return a;},[outline,top,h,paved]);return <><Blocks data={data}/><mesh position={[0,-.525,0]} rotation={[-Math.PI/2,0,0]} receiveShadow><planeGeometry args={[200,200]}/><shadowMaterial opacity={.16}/></mesh></>;}
export function BrickPanel({w,h,c='#a87b5f'}:{w:number;h:number;c?:string}){const data=useMemo(()=>{const a:Block[]=[];for(let j=0;j<h/.14;j++)for(let i=0;i<w/.30;i++){const x=-w/2+i*.3+.15+(j%2)*.15;if(x>w/2-.10)continue;a.push({p:[x,j*.14+.065,0],s:[.28,.125,.20],c:new T.Color(c).multiplyScalar(.9+(Math.sin(i*23+j*17)+1)*.085).getStyle()});}return a;},[w,h,c]);return <><Box p={[0,h/2,-.035]} s={[w,h,.13]} c='#b9ab91'/><Blocks data={data}/></>;}
